// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIWSVE9PptaEULMyaOARegeDqqUUz22M',
    appId: '1:668365067765:web:27d7d60dae8e79d2e4fcbc',
    messagingSenderId: '668365067765',
    projectId: 'authplan-1ebf8',
    authDomain: 'authplan-1ebf8.firebaseapp.com',
    storageBucket: 'authplan-1ebf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wAYHJdNafI9qyKRRdSknz-l3Dg9TXmI',
    appId: '1:668365067765:android:71484d4cc39352e0e4fcbc',
    messagingSenderId: '668365067765',
    projectId: 'authplan-1ebf8',
    storageBucket: 'authplan-1ebf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZREvwCnTqCrnLK8yqWAOsw6yH9AxaB0',
    appId: '1:668365067765:ios:6b5f5ea3aaff4b9de4fcbc',
    messagingSenderId: '668365067765',
    projectId: 'authplan-1ebf8',
    storageBucket: 'authplan-1ebf8.appspot.com',
    iosClientId: '668365067765-d2j1miggdk10rgaqna2jv1aifes2o782.apps.googleusercontent.com',
    iosBundleId: 'com.example.planApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZREvwCnTqCrnLK8yqWAOsw6yH9AxaB0',
    appId: '1:668365067765:ios:6b5f5ea3aaff4b9de4fcbc',
    messagingSenderId: '668365067765',
    projectId: 'authplan-1ebf8',
    storageBucket: 'authplan-1ebf8.appspot.com',
    iosClientId: '668365067765-d2j1miggdk10rgaqna2jv1aifes2o782.apps.googleusercontent.com',
    iosBundleId: 'com.example.planApp',
  );
}
